<?php
/**
* autoGenerated on 2011-10-31
* @package models
* @subpackage 
* @class BASE_users
* @property userRoles $userRole
* @method userRoles getUserRole()
*/
class BASE_users extends abstractModel{

	protected $datas = array(
		'userId' => 0, //int(10) unsigned
		'userRole' => 0, //int(10) unsigned
		'login' => '', //varchar(255)
		'password' => '', //varchar(255)
		'email' => '', //varchar(255)
		'active' => 0, //tinyint(1) unsigned
	);

	static protected $filters = array();

	static protected $hasOne = array(
		// 'relName'=> array('modelName'=>'modelName','relType'=>'ignored|dependOn|requireBy',['localField'=>'fldNameIfNotPrimaryKey','foreignField'=>'fldNameIfNotPrimaryKey','foreignDefault'=>'ForeignFieldValueOnDelete'])
		'userRole' => array(
			'modelName'=>'userRoles',
			'localField'=>'userRole',
			'relType'=>'dependOn',
		),
	);
	static protected $hasMany = array(
		//   'relName'=> array('modelName'=>'modelName','relType'=>'ignored|dependOn|requireBy','foreignField'=>'fieldNameIfNotPrimaryKey'[,'localField'=>'fieldNameIfNotPrimaryKey','foreignDefault'=>'ForeignFieldValueOnDelete','orderBy'=>'orderBy'=>'fieldName [asc|desc][,fieldName [asc|desc],...]']),
		//or 'relName'=> array('modelName'=>'modelName','linkTable'=>'tableName','linkLocalField'=>'fldName','linkForeignField'=>'fldName','relType'=>'ignored|dependOn|requireBy',['orderBy'=>'fieldName [asc|desc][,fieldName [asc|desc],...]']),
	);

	/** database link */
	static protected $dbConnectionDescriptor = DB_CONNECTION;
	protected $dbAdapter = null;

	static protected $modelName = 'BASE_users';
	static protected $tableName = 'users';
	static protected $primaryKey = 'userId';

	/**
	* field information about type, default values and so on
	*/
	static protected $datasDefs = array(
		'userId' => array('Type'=>'int(10) unsigned', 'Extra'=>'auto_increment', 'Null' =>'NO', 'Key' =>'PRI', 'Default'=>0),
		'userRole' => array('Type'=>'int(10) unsigned', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'', 'Default'=>0),
		'login' => array('Type'=>'varchar(255)', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'UNI', 'Default'=>''),
		'password' => array('Type'=>'varchar(255)', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'', 'Default'=>''),
		'email' => array('Type'=>'varchar(255)', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'', 'Default'=>''),
		'active' => array('Type'=>'tinyint(1) unsigned', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'', 'Default'=>0),
	);

	static public function getNew(){
		return abstractModel::getModelInstance('users');
	}

	static public function getInstance($PK=null){
		return abstractModel::getModelInstance('users',$PK);
	}
	static public function getMultipleInstances(array $PKs){
		return abstractModel::getMultipleModelInstances('users',$PKs);
	}
	static public function getFilteredInstances($filter=null){
		return abstractModel::getFilteredModelInstances('users',$filter);
	}
	static public function getFilteredInstance($filter=null){
		return abstractModel::getFilteredModelInstance('users',$filter);
	}
	static public function getFilteredInstancesByField($field,$filterType,$args=null){
		return abstractModel::getFilteredModelInstancesByField('users',$field,$filterType,$args);
	}
	static public function getInstanceFromDatas($datas,$dontOverideIfExists=false,$bypassFilters=false){
		return abstractModel::getModelInstanceFromDatas('users',$datas,$dontOverideIfExists,$bypassFilters);
	}
	static public function getAllInstances($withRelated=null,$orderedBY=null){
		return abstractModel::getAllModelInstances('users',$withRelated,$orderedBY);
	}
	static public function getPagedInstances($filter=null,$pageId=1,$pageSize=10,$withRelated=null){
		return abstractModel::getPagedModelInstances('users',$filter,$pageId,$pageSize,$withRelated);
	}
	static public function _setPagedNav(array $sliceAttrs=null){
		return abstractModel::_setModelPagedNav('users',$sliceAttrs);
	}
	static public function _getSupportedAddons(){
		return abstractModel::_modelGetSupportedAddons('users');
	}
	static public function _supportsAddon($modelAddon,$caseInsensitive=false){
		return abstractModel::_modelGetSupportedAddons('users',$modelAddon,$caseInsensitive);
	}
	static public function getCount($filter=null){
		return abstractModel::getModelCount('users',$filter);
	}

	/**
	* permit to access static dynamic methods such as getByFieldnameLessThan for php >= 5.3
	* where fieldName is a modelName::$datas key
	* (will work like this: modelName::getByFieldnameLessThan($value));
	* In the time waiting for this to be handled in future version of php (at this time latest stable release is still 5.2)
	* we can use it like this: modelName::__callstatic('getByFieldnameLessThan',array($value))
	* (with late stating binding enable we should move this to abstractModel and replace '$modelName' by static)
	*/
	static public function __callstatic($m,$a){
		#- manage common filter getter
		if(preg_match('!getBy('.implode('|',array_keys(self::$datasDefs)).')((?:(?:Less|Greater)(?:Equal)?Than)|Between|(?:Not)?(?:Null|Equal|Like|In))$!',$m,$match)){
			return call_user_func('abstractModel::getFilteredModelInstancesByField','users',$match[1],$match[2],$a);
		}
	}
	/**
	* return a static property of the model (even protected).
	* @param string $propName name of the static property to retrieve.
	* @return mixed
	*/
	static public function _getStatic($propName){
		return abstractModel::_getModelStaticProp('users',$propName);
	}
	static public function _setDbConnectionDescriptor($descriptor,$detach=false){
		self::$dbConnectionDescriptor = $descriptor;
		if( $detach){
			abstractModel::getModelLivingInstances('users')->detach();
		}
	}
	static public function _getDbAdapter(){
		return abstractModel::getModelDbAdapter('users');
	}
	static public function hasRelDefs($relType=null,$returnDef=false){
		return abstractModel::modelHasRelDefs('users',$relType,$returnDef);
	}

	###--- AUTOGENERATION PROCESS PROPOSED THOOSE ADDITIONAL METHODS ---###
	/**
	* check if the given value already exists in database
	*/
	static public function checkLoginExists($v,$returnInstance=false,$ignoredPK=null){
		return self::modelCheckFieldDatasExists('users', 'login', $v, $returnInstance, $ignoredPK);
	}
	
}
