<?php
/**
* autoGenerated on 2011-10-31
* @package models
* @subpackage 
* @class BASE_userRights
* @property userRightDomains $userRightDomain
* @method userRightDomains getUserRightDomain()
* @property userRolesCollection $userRoles
* @method $this appendUserRoles()
* @method userRoles appendNewUserRoles()
* @method $this setUserRolesCollection()
* @method userRolesCollection getUserRoles() @see getRelated() methods for more infos
* @method userRolesCollection getFilteredUserRoles($propertyName,$exp,$comparisonOperator=null) sort of $this->getRelated()->getFilteredBy() trying to be optimized
*/
class BASE_userRights extends abstractModel{

	protected $datas = array(
		'rightId' => 0, //int(10) unsigned
		'userRightDomain' => 0, //int(10) unsigned
		'name' => '', //varchar(255)
	);

	static protected $filters = array();

	static protected $hasOne = array(
		// 'relName'=> array('modelName'=>'modelName','relType'=>'ignored|dependOn|requireBy',['localField'=>'fldNameIfNotPrimaryKey','foreignField'=>'fldNameIfNotPrimaryKey','foreignDefault'=>'ForeignFieldValueOnDelete'])
		'userRightDomain' => array(
			'modelName'=>'userRightDomains',
			'localField'=>'userRightDomain',
			'relType'=>'dependOn',
		),
	);
	static protected $hasMany = array(
		//   'relName'=> array('modelName'=>'modelName','relType'=>'ignored|dependOn|requireBy','foreignField'=>'fieldNameIfNotPrimaryKey'[,'localField'=>'fieldNameIfNotPrimaryKey','foreignDefault'=>'ForeignFieldValueOnDelete','orderBy'=>'orderBy'=>'fieldName [asc|desc][,fieldName [asc|desc],...]']),
		//or 'relName'=> array('modelName'=>'modelName','linkTable'=>'tableName','linkLocalField'=>'fldName','linkForeignField'=>'fldName','relType'=>'ignored|dependOn|requireBy',['orderBy'=>'fieldName [asc|desc][,fieldName [asc|desc],...]']),
		'userRoles' => array(
			'modelName'=>'userRoles',
			'linkTable'=>'userRoles_userRights',
			'linkLocalField'=>'userRight',
			'linkForeignField'=>'userRole',
			'relType'=>'ignored',
		),
	);

	/** database link */
	static protected $dbConnectionDescriptor = DB_CONNECTION;
	protected $dbAdapter = null;

	static protected $modelName = 'BASE_userRights';
	static protected $tableName = 'userRights';
	static protected $primaryKey = 'rightId';

	/**
	* field information about type, default values and so on
	*/
	static protected $datasDefs = array(
		'rightId' => array('Type'=>'int(10) unsigned', 'Extra'=>'auto_increment', 'Null' =>'NO', 'Key' =>'PRI', 'Default'=>0),
		'userRightDomain' => array('Type'=>'int(10) unsigned', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'MUL', 'Default'=>0),
		'name' => array('Type'=>'varchar(255)', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'', 'Default'=>''),
	);

	static public function getNew(){
		return abstractModel::getModelInstance('userRights');
	}

	static public function getInstance($PK=null){
		return abstractModel::getModelInstance('userRights',$PK);
	}
	static public function getMultipleInstances(array $PKs){
		return abstractModel::getMultipleModelInstances('userRights',$PKs);
	}
	static public function getFilteredInstances($filter=null){
		return abstractModel::getFilteredModelInstances('userRights',$filter);
	}
	static public function getFilteredInstance($filter=null){
		return abstractModel::getFilteredModelInstance('userRights',$filter);
	}
	static public function getFilteredInstancesByField($field,$filterType,$args=null){
		return abstractModel::getFilteredModelInstancesByField('userRights',$field,$filterType,$args);
	}
	static public function getInstanceFromDatas($datas,$dontOverideIfExists=false,$bypassFilters=false){
		return abstractModel::getModelInstanceFromDatas('userRights',$datas,$dontOverideIfExists,$bypassFilters);
	}
	static public function getAllInstances($withRelated=null,$orderedBY=null){
		return abstractModel::getAllModelInstances('userRights',$withRelated,$orderedBY);
	}
	static public function getPagedInstances($filter=null,$pageId=1,$pageSize=10,$withRelated=null){
		return abstractModel::getPagedModelInstances('userRights',$filter,$pageId,$pageSize,$withRelated);
	}
	static public function _setPagedNav(array $sliceAttrs=null){
		return abstractModel::_setModelPagedNav('userRights',$sliceAttrs);
	}
	static public function _getSupportedAddons(){
		return abstractModel::_modelGetSupportedAddons('userRights');
	}
	static public function _supportsAddon($modelAddon,$caseInsensitive=false){
		return abstractModel::_modelGetSupportedAddons('userRights',$modelAddon,$caseInsensitive);
	}
	static public function getCount($filter=null){
		return abstractModel::getModelCount('userRights',$filter);
	}

	/**
	* permit to access static dynamic methods such as getByFieldnameLessThan for php >= 5.3
	* where fieldName is a modelName::$datas key
	* (will work like this: modelName::getByFieldnameLessThan($value));
	* In the time waiting for this to be handled in future version of php (at this time latest stable release is still 5.2)
	* we can use it like this: modelName::__callstatic('getByFieldnameLessThan',array($value))
	* (with late stating binding enable we should move this to abstractModel and replace '$modelName' by static)
	*/
	static public function __callstatic($m,$a){
		#- manage common filter getter
		if(preg_match('!getBy('.implode('|',array_keys(self::$datasDefs)).')((?:(?:Less|Greater)(?:Equal)?Than)|Between|(?:Not)?(?:Null|Equal|Like|In))$!',$m,$match)){
			return call_user_func('abstractModel::getFilteredModelInstancesByField','userRights',$match[1],$match[2],$a);
		}
	}
	/**
	* return a static property of the model (even protected).
	* @param string $propName name of the static property to retrieve.
	* @return mixed
	*/
	static public function _getStatic($propName){
		return abstractModel::_getModelStaticProp('userRights',$propName);
	}
	static public function _setDbConnectionDescriptor($descriptor,$detach=false){
		self::$dbConnectionDescriptor = $descriptor;
		if( $detach){
			abstractModel::getModelLivingInstances('userRights')->detach();
		}
	}
	static public function _getDbAdapter(){
		return abstractModel::getModelDbAdapter('userRights');
	}
	static public function hasRelDefs($relType=null,$returnDef=false){
		return abstractModel::modelHasRelDefs('userRights',$relType,$returnDef);
	}
}
