<?php
/**
* autoGenerated on 2011-10-31
* @package models
* @subpackage 
* @class BASE_userRoles
* @property userRightsCollection $userRights
* @method $this appendUserRights()
* @method userRights appendNewUserRights()
* @method $this setUserRightsCollection()
* @method userRightsCollection getUserRights() @see getRelated() methods for more infos
* @method userRightsCollection getFilteredUserRights($propertyName,$exp,$comparisonOperator=null) sort of $this->getRelated()->getFilteredBy() trying to be optimized
* @property usersCollection $users
* @method $this appendUsers()
* @method users appendNewUsers()
* @method $this setUsersCollection()
* @method usersCollection getUsers() @see getRelated() methods for more infos
* @method usersCollection getFilteredUsers($propertyName,$exp,$comparisonOperator=null) sort of $this->getRelated()->getFilteredBy() trying to be optimized
*/
class BASE_userRoles extends abstractModel{

	protected $datas = array(
		'roleId' => 0, //int(10) unsigned
		'name' => '', //varchar(255)
		'active' => 1, //tinyint(1) unsigned
	);

	static protected $filters = array();

	static protected $hasOne = array(
		// 'relName'=> array('modelName'=>'modelName','relType'=>'ignored|dependOn|requireBy',['localField'=>'fldNameIfNotPrimaryKey','foreignField'=>'fldNameIfNotPrimaryKey','foreignDefault'=>'ForeignFieldValueOnDelete'])
	);
	static protected $hasMany = array(
		//   'relName'=> array('modelName'=>'modelName','relType'=>'ignored|dependOn|requireBy','foreignField'=>'fieldNameIfNotPrimaryKey'[,'localField'=>'fieldNameIfNotPrimaryKey','foreignDefault'=>'ForeignFieldValueOnDelete','orderBy'=>'orderBy'=>'fieldName [asc|desc][,fieldName [asc|desc],...]']),
		//or 'relName'=> array('modelName'=>'modelName','linkTable'=>'tableName','linkLocalField'=>'fldName','linkForeignField'=>'fldName','relType'=>'ignored|dependOn|requireBy',['orderBy'=>'fieldName [asc|desc][,fieldName [asc|desc],...]']),
		'userRights' => array(
			'modelName'=>'userRights',
			'linkTable'=>'userRoles_userRights',
			'linkLocalField'=>'userRole',
			'linkForeignField'=>'userRight',
			'relType'=>'ignored',
		),
		'users' => array(
			'modelName'=>'users',
			'foreignField'=>'userRole',
			'relType'=>'requiredBy',
		),
	);

	/** database link */
	static protected $dbConnectionDescriptor = DB_CONNECTION;
	protected $dbAdapter = null;

	static protected $modelName = 'BASE_userRoles';
	static protected $tableName = 'userRoles';
	static protected $primaryKey = 'roleId';

	/**
	* field information about type, default values and so on
	*/
	static protected $datasDefs = array(
		'roleId' => array('Type'=>'int(10) unsigned', 'Extra'=>'auto_increment', 'Null' =>'NO', 'Key' =>'PRI', 'Default'=>0),
		'name' => array('Type'=>'varchar(255)', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'', 'Default'=>''),
		'active' => array('Type'=>'tinyint(1) unsigned', 'Extra'=>'', 'Null' =>'NO', 'Key' =>'', 'Default'=>1),
	);

	static public function getNew(){
		return abstractModel::getModelInstance('userRoles');
	}

	static public function getInstance($PK=null){
		return abstractModel::getModelInstance('userRoles',$PK);
	}
	static public function getMultipleInstances(array $PKs){
		return abstractModel::getMultipleModelInstances('userRoles',$PKs);
	}
	static public function getFilteredInstances($filter=null){
		return abstractModel::getFilteredModelInstances('userRoles',$filter);
	}
	static public function getFilteredInstance($filter=null){
		return abstractModel::getFilteredModelInstance('userRoles',$filter);
	}
	static public function getFilteredInstancesByField($field,$filterType,$args=null){
		return abstractModel::getFilteredModelInstancesByField('userRoles',$field,$filterType,$args);
	}
	static public function getInstanceFromDatas($datas,$dontOverideIfExists=false,$bypassFilters=false){
		return abstractModel::getModelInstanceFromDatas('userRoles',$datas,$dontOverideIfExists,$bypassFilters);
	}
	static public function getAllInstances($withRelated=null,$orderedBY=null){
		return abstractModel::getAllModelInstances('userRoles',$withRelated,$orderedBY);
	}
	static public function getPagedInstances($filter=null,$pageId=1,$pageSize=10,$withRelated=null){
		return abstractModel::getPagedModelInstances('userRoles',$filter,$pageId,$pageSize,$withRelated);
	}
	static public function _setPagedNav(array $sliceAttrs=null){
		return abstractModel::_setModelPagedNav('userRoles',$sliceAttrs);
	}
	static public function _getSupportedAddons(){
		return abstractModel::_modelGetSupportedAddons('userRoles');
	}
	static public function _supportsAddon($modelAddon,$caseInsensitive=false){
		return abstractModel::_modelGetSupportedAddons('userRoles',$modelAddon,$caseInsensitive);
	}
	static public function getCount($filter=null){
		return abstractModel::getModelCount('userRoles',$filter);
	}

	/**
	* permit to access static dynamic methods such as getByFieldnameLessThan for php >= 5.3
	* where fieldName is a modelName::$datas key
	* (will work like this: modelName::getByFieldnameLessThan($value));
	* In the time waiting for this to be handled in future version of php (at this time latest stable release is still 5.2)
	* we can use it like this: modelName::__callstatic('getByFieldnameLessThan',array($value))
	* (with late stating binding enable we should move this to abstractModel and replace '$modelName' by static)
	*/
	static public function __callstatic($m,$a){
		#- manage common filter getter
		if(preg_match('!getBy('.implode('|',array_keys(self::$datasDefs)).')((?:(?:Less|Greater)(?:Equal)?Than)|Between|(?:Not)?(?:Null|Equal|Like|In))$!',$m,$match)){
			return call_user_func('abstractModel::getFilteredModelInstancesByField','userRoles',$match[1],$match[2],$a);
		}
	}
	/**
	* return a static property of the model (even protected).
	* @param string $propName name of the static property to retrieve.
	* @return mixed
	*/
	static public function _getStatic($propName){
		return abstractModel::_getModelStaticProp('userRoles',$propName);
	}
	static public function _setDbConnectionDescriptor($descriptor,$detach=false){
		self::$dbConnectionDescriptor = $descriptor;
		if( $detach){
			abstractModel::getModelLivingInstances('userRoles')->detach();
		}
	}
	static public function _getDbAdapter(){
		return abstractModel::getModelDbAdapter('userRoles');
	}
	static public function hasRelDefs($relType=null,$returnDef=false){
		return abstractModel::modelHasRelDefs('userRoles',$relType,$returnDef);
	}
}
