#- <?php echo "Access Denied!"; exit(); ?>
#- @package simpleMVC
#- @subpackage config
#- GENERAL CONFIG FOR APPS
#- ADD ANY CONSTANTS YOU MAY REQUIRE HERE

#- ACTIVATE/DEACTIVATE DEVELOPPMENT STATE (DEBUG LEVEL)
DEVEL_MODE = true

#- DEFAULT DISPATCHING
DEFAULT_DISPATCH = pages:index
ERROR_DISPATCH = pages:error
#- DATABASE CONNECTION
# DB_CONNECTION  = mysqldb://dbname;dbhost;dbuser;dbpass


#- SOME PATH CONFIGURATION REQUIRED OR USEFULL FOR FURTHER DEVELOPPMENT.
ROOT_URL     = http://example.com/
MODELS_DIR   = %LIB_DIR%/models
APP_URL      = %ROOT_URL%/%FRONT_NAME%
APP_DIR      = %ROOT_DIR%/%FRONT_NAME%

#- PATH TO GUI IMAGES (USED IN BACKOFFICE GENERATION)
GUI_IMG_URL  = %ROOT_URL%/images
GUI_IMG_DIR  = %ROOT_DIR%/images

#- PATH USED FOR FILEMANAGER HELPER
USER_DATAS_DIR = %ROOT_DIR%/userFiles
USER_DATAS_URL = %ROOT_URL%/userFiles

# DO WE USE REWITES RULES
USE_REWRITE_RULES = TRUE

#- CACHE CONFIG
CACHE_MANAGER_DEFAULT_BACKEND = fileCacheBackend
CACHE_MANAGER_ENABLE = false
CACHE_MANAGER_AUTOCLEAR = true
CACHE_MANAGER_TTL = 30 minutes
CACHE_FILE_ROOT_DIR = %APP_DIR%/_cache
CACHE_FILE_USE_SUBDIRS = false

#- FORCE JS HELPER OUTPUT IN HEADER
JS_TO_HEAD = true